# Default Configuration
version: 1

# Disable previously created loggers and update the root logger at the instant
# the configuration file is fed.
disable_existing_loggers: true

# Logging formatter definition
# For more details on format types,
# visit - 'https://docs.python.org/3/library/logging.html#logrecord-attributes
formatters:
  default:
    datefmt: "[%x %X]"
    format: "%(message)s"

# Logging handlers
# For a list of pre-defined handlers, visit -
# 'https://docs.python.org/3/library/logging.handlers.html#module-logging.handlers'
handlers:
  rich:
    class: finvestor.utils.logger.RichHandler


# Root Logger Configuration
root:
  level: NOTSET
  handlers: [rich]
  propogate: yes

# List of child loggers with pre-defined levels
loggers:
  finvestor:
    level: DEBUG
