# Default Configuration
version: 1

# Disable previously created loggers and update the root logger at the instant
# the configuration file is fed.
disable_existing_loggers: true

# # Logging formatter definition
# # For more details on format types,
# # visit - 'https://docs.python.org/3/library/logging.html#logrecord-attributes
formatters:
  simple:
    datefmt: "%Y-%m-%dT%H:%M:%S%z"
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"

# Logging handlers
# For a list of pre-defined handlers, visit -
# 'https://docs.python.org/3/library/logging.handlers.html#module-logging.handlers'
handlers:
  simple:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  rich:
    class: finvestor.core.logging.RichHandler

# Root Logger Configuration
root:
  # Logger Level -
  level: DEBUG
  handlers: [rich]
  # Stop propogation from child to parent in Logging hierarchy
  propogate: no

loggers:
  finvestor:
    level: DEBUG
  httpx:
    level: INFO
  matplotlib:
    level: INFO
  PIL:
    level: INFO
